use tauri_specta::{collect_commands, collect_events, Builder, ErrorHandlingMode};

use crate::{
    capture_coordinator, capture_session, data, events, history_reprocessing, hotkey, indicator,
    local_asr_model, macos_permissions, pipeline, providers, readiness, realtime_asr_model,
    recording, recording_storage,
};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            capture_coordinator::start_capture,
            capture_coordinator::stop_capture,
            providers::list_provider_catalog,
            pipeline::process_uploaded_audio,
            capture_session::read_capture_snapshot,
            capture_session::abort_capture_session,
            data::initialize_local_data,
            data::list_personas,
            data::set_default_persona,
            data::create_persona,
            data::update_persona,
            data::delete_persona,
            data::create_hotword,
            data::list_hotwords,
            data::add_hotwords,
            data::replace_hotwords,
            data::update_hotword,
            data::delete_hotword,
            data::enabled_hotword_context,
            data::create_history_record,
            data::list_history_records,
            data::history_statistics,
            data::delete_history_record,
            history_reprocessing::read_retained_recording,
            history_reprocessing::reprocess_history_audio,
            history_reprocessing::refine_history_text,
            data::read_app_config,
            data::update_app_config,
            recording::list_audio_devices,
            readiness::read_input_readiness,
            local_asr_model::local_asr_model_info,
            local_asr_model::download_local_asr_model,
            local_asr_model::delete_local_asr_model,
            local_asr_model::verify_local_asr_model,
            realtime_asr_model::realtime_asr_model_info,
            realtime_asr_model::download_realtime_asr_model,
            realtime_asr_model::verify_realtime_asr_model,
            realtime_asr_model::set_realtime_preview_enabled,
            realtime_asr_model::delete_realtime_asr_model,
            macos_permissions::request_macos_permission,
            macos_permissions::open_macos_privacy_settings,
            recording_storage::recording_storage_info,
            recording_storage::open_recordings_directory,
            recording_storage::clear_retained_recordings,
            hotkey::register_hotkey,
            hotkey::register_both_hotkeys,
            hotkey::unregister_hotkey,
            indicator::update_indicator_status,
        ])
        .events(collect_events![
            events::CaptureSnapshotEvent,
            events::HistoryChangedEvent,
            events::RealtimeAsrDownloadProgressEvent,
            events::RecordingErrorEvent,
            events::RecordingLimitWarningEvent,
            events::LocalAsrDownloadProgressEvent,
        ])
}
